FROM analogj/crossbuild as base

RUN apt-get update \
 && apt-get install -q -y pkg-config

# Install GOLANG
ENV GO_VERSION 1.10.8
RUN curl -fsSL "https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz" \
	| tar -xzC /usr/local

ENV PATH="/go/bin:/usr/local/go/bin:${PATH}" \
	GOPATH="/go"

WORKDIR /go

COPY scripts /scripts

# set env vars
ENV PKG_CONFIG_PATH="/usr/lib/pkgconfig/:/usr/local/lib/pkgconfig/:/usr/local/lib/libgit2/lib/pkgconfig:/usr/local/lib/openssl/lib/pkgconfig:/usr/local/lib/libssh2"

RUN /scripts/configure.sh


FROM debian:jessie-slim as slim

RUN mkdir -p /usr/local/lib/libgit2 \
    && mkdir -p /usr/local/lib/openssl \
    && mkdir -p /usr/local/lib/libssh2

COPY --from=base /usr/local/lib/libgit2/ /usr/local/lib/libgit2/
COPY --from=base /usr/local/lib/openssl/ /usr/local/lib/openssl/
COPY --from=base /usr/local/lib/libssh2/ /usr/local/lib/libssh2/
